#!/bin/bash 
#
# Post push hook for Docker Automated Build.
#
# This hook adds the 'latest' tag to the image.
#
set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

source ./hooks/pre_build

echo "Environment variables:
    IMAGE_NAME=$IMAGE_NAME
    DOCKER_REPO=$DOCKER_REPO
    DOCKER_TAG=$DOCKER_TAG
    SOURCE_BRANCH=$SOURCE_BRANCH
"

if [[ "$DOCKER_TAG" =~ ^[0-9.]+$ ]]; then

    DOCKER_NEWTAG="latest"
    echo "Adding tag '$DOCKER_NEWTAG' to image..."
    docker tag $IMAGE_NAME ${DOCKER_REPO}:$DOCKER_NEWTAG
    echo "Pushing image..."
    docker push ${DOCKER_REPO}:$DOCKER_NEWTAG

else
  echo "Nothing to do."
fi

echo "post_push hook terminated successfully."
