#!/bin/bash -e
echo "pre_build hook started."
[ -n "$SOURCE_BRANCH" ]  || SOURCE_BRANCH=$(git symbolic-ref -q --short HEAD)
 

if [[ "${SOURCE_BRANCH}" =~ "master" ]]; then 
	VERSION=latest
elif [[ "${SOURCE_BRANCH/-*/}" =~ ^[0-9.]+*$ ]]; then
    VERSION=${SOURCE_BRANCH/-*/}


fi
 
[ -n "$IMAGE_NAME" ] || IMAGE_NAME=meyay/unionfs-mount:${SOURCE_BRANCH}

echo "Environment variables:
  IMAGE_NAME=$IMAGE_NAME
  DOCKER_REPO=$DOCKER_REPO
  DOCKER_TAG=$DOCKER_TAG
  SOURCE_BRANCH=$SOURCE_BRANCH
  VERSION=$VERSION
  DOCKERFILE_PATH=$DOCKERFILE_PATH
"

echo "pre_build hook terminated successfully."
